---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zrq.
--- DateTime: 2026/3/3 20:35
---
local limitKeyPrefix = KEYS[1]
local receiveListKeyPrefix = KEYS[2]
local couponId = KEYS[3]

local userIds = cjson.decode(ARGV[1]);
local couponIds = cjson.decode(ARGV[2]);
local nowTime = tonumber(ARGV[3]);
local expireTime = tonumber(ARGV[4]);

for i, userId in ipairs(userIds) do
    local receiveKey = receiveListKeyPrefix .. userId;
    local couponId_receiveId = couponIds[i]
    if couponId_receiveId then
        redis.call("ZADD", receiveKey, nowTime, couponId_receiveId);
        local limitKey = limitKeyPrefix .. userId .. couponId;
        redis.call("INCR", limitKey);
        redis.call("EXPIRE", limitKey, expireTime);
    end
end
